Exception on /knowledgeGraphServer/getAnswer [GET]
Traceback (most recent call last):
  File "D:\ToolsForEdit\Anaconda\envs\python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\ToolsForEdit\Anaconda\envs\python38\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\ToolsForEdit\Anaconda\envs\python38\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\ToolsForEdit\Anaconda\envs\python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\ToolsForEdit\Anaconda\envs\python38\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\ToolsForEdit\Anaconda\envs\python38\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Edit\Python\python38\KnowledgeController.py", line 56, in getAnswer
    if errorCouple['isError'] == True:
KeyError: 'isError'
sdfsdf
{'question': '交互界面请求的问题'}
Exception on /knowledgeGraphServer/getAnswer [GET]
Traceback (most recent call last):
  File "D:\ToolsForEdit\Anaconda\envs\python38\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\ToolsForEdit\Anaconda\envs\python38\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\ToolsForEdit\Anaconda\envs\python38\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\ToolsForEdit\Anaconda\envs\python38\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\ToolsForEdit\Anaconda\envs\python38\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\ToolsForEdit\Anaconda\envs\python38\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Edit\Python\python38\KnowledgeController.py", line 56, in getAnswer
    if errorCouple['isError'] == True:
KeyError: 'isError'
